name: Create a tag on push on main

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Version tag
        id: get_version_tag
        run: |
          export TAG=$(head CHANGELOG.md -n1 | sed -e 's/^# \[\([0-9.]\+\)\].*$/\1/g')
          echo "::set-output name=TAG::$TAG"

      - name: Get latest commit hash
        id: get_commit_hash
        run: echo ::set-output name=COMMIT_HASH::$(git rev-parse --short HEAD)
      
      - name: Config git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Create tag
        run: |
          git tag -a ${{ steps.get_version_tag.TAG }} v${{ steps.get_commit_hash.outputs.COMMIT_HASH }} -m "Release v$TAG"
          git push origin --tags
