name: Delete Branch After Merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        if: >
         github.event.pull_request.merged == true &&
         (github.event.pull_request.base.ref == 'develop' || github.event.pull_request.base.ref == 'qa' || github.event.pull_request.base.ref == 'main') &&
         (github.event.pull_request.head.ref != 'develop' && github.event.pull_request.head.ref != 'qa' && github.event.pull_request.head.ref != 'main')
        run: |
          git push origin --delete ${{ github.event.pull_request.head.ref }}